### ISSUE TITLE
Guía rápida de Jenkins

### ISSUE THREAD

**Issue by antoniosantos-inetum** [srayuso/unir-build-tools#1]
Hola, Roberto:

Soy Antonio Santos, alumno de Master Devops. Tengo una duda acerca de la guía rápida de Jenkins, concretamente el paso siguiente:

_Copia el secreto del agente 1 en la variable JENKINS_DOCKER_AGENT_SECRET del Makefile y el secreto del agente 2 en la variable JENKINS_MAVEN_AGENT_SECRET._

Trato de crear nuevas credenciales en los dos agentes que indicas a crear, pero luego no sé sacar la información necesaria para editar el Makefile.

Si pudieras dar más detalle, te lo agradecería. 

Muchas gracias. Un saludo,

Antonio.

**Comment by antoniosantos-inetum** [comment]
He encontrado la forma de configurarlo en el video recomendado en Canvas. Pongo el punto exacto:

https://www.youtube.com/watch?v=FX322RVNGj4&t=6742

Muchas gracias!!

**Comment by srayuso** [comment]
Gracias por el aviso Antonio. He actualizado el readme con instrucciones sobre dónde encontrar el secreto.
